"use client";
import {useEffect,useState} from "react";
import {supabaseBrowser} from "../lib/supabase";
const money=n=>new Intl.NumberFormat("vi-VN").format(Number(n||0))+"đ";
export default function Home(){const sb=supabaseBrowser();const[products,setProducts]=useState([]);const[cats,setCats]=useState([]);const[q,setQ]=useState("");const[loading,setLoading]=useState(true);
useEffect(()=>{(async()=>{const [{data:p},{data:c}]=await Promise.all([sb.from("products").select("*").eq("active",true).order("created_at",{ascending:false}),sb.from("categories").select("*").eq("active",true).order("sort_order")]);setProducts(p||[]);setCats(c||[]);setLoading(false)})()},[]);
const filtered=products.filter(p=>(p.name+" "+(p.platform||"")+" "+(p.game||"")).toLowerCase().includes(q.toLowerCase()));
return <><Header q={q} setQ={setQ}/><section className="hero"><div><span className="pill">✦ NEXORA DIGITAL MARKETPLACE</span><h1>Mua sản phẩm số<br/><em>nhanh • gọn • an tâm.</em></h1><p>Nạp số dư, chọn sản phẩm và nhận đơn hàng ngay. Tối ưu cho trải nghiệm trên điện thoại.</p><div className="actions"><a className="btn" href="/products">Khám phá sản phẩm →</a><a className="btn ghost" href="/wallet">Nạp tiền</a></div></div><div className="heroArt"><div className="n">N</div><b>NEXORA</b><small>DIGITAL MARKETPLACE</small></div></section>
<section className="stats"><div><b>24/7</b><span>Hệ thống</span></div><div><b>{products.length}+</b><span>Sản phẩm</span></div><div><b>⚡</b><span>Giao nhanh</span></div><div><b>🔐</b><span>Bảo mật</span></div></section>
<section className="wrap"><div className="title"><div><h2>🔥 Sản phẩm nổi bật</h2><p>{cats.length?cats.length+" danh mục đang hoạt động":"Sản phẩm cập nhật trực tiếp từ Supabase"}</p></div><a href="/products">Xem tất cả →</a></div>{loading?<div className="empty">Đang tải sản phẩm...</div>:<div className="grid">{filtered.slice(0,8).map(p=><ProductCard key={p.id} p={p}/>)}</div>}{!loading&&!filtered.length&&<div className="empty">Chưa có sản phẩm phù hợp.</div>}</section><Footer/></>}
function ProductCard({p}){return <article className="card"><a href={"/products/"+p.id}><div className="thumb">{p.image_url?<img src={p.image_url} alt=""/>:<span>✦</span>}</div></a><small>{p.platform||"Digital"}{p.game?" · "+p.game:""} · Kho {p.stock}</small><h3>{p.name}</h3><p>{p.description||"Sản phẩm số chất lượng."}</p><div className="bottom"><strong>{money(p.price)}</strong><a href={"/products/"+p.id}>Chi tiết</a></div></article>}
function Header({q,setQ}){return <header><a className="brand" href="/"><span>N</span><div><b>NEXORA</b><small>DIGITAL MARKETPLACE</small></div></a><nav><a href="/">Trang chủ</a><a href="/products">Sản phẩm</a><a href="/wallet">Ví</a><a href="/orders">Đơn hàng</a><a href="/support">💬 Hỗ trợ</a><a href="/account">Tài khoản</a></nav><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Tìm sản phẩm..."/><a className="login" href="/account">Tài khoản</a></header>}
function Footer(){return <footer><b>NEXORA</b><span>Digital Marketplace hiện đại.</span><span>© 2026 NEXORA</span></footer>}
